In [1]:
import pandas as pd

data = pd.read_excel("time_series_375_preprocess_en-2.xlsx")
data_test = pd.read_excel("time_series_test_110_preprocess_en-2.xlsx")

In [16]:
print(f"Number of rows in the training dataset: {len(data)}")
print(f"Number of rows in the test dataset: {len(data_test)}")
print(f"Number of features in the training dataset: {data.shape[1]}")


data.head()

Number of rows in the training dataset: 6120
Number of rows in the test dataset: 757
Number of features in the training dataset: 81

,PATIENT_ID,RE_DATE,age,gender,Admission time,Discharge time,outcome,Hypersensitive cardiac troponinI,hemoglobin,Serum chloride,...,mean corpuscular hemoglobin,Activation of partial thromboplastin time,Hypersensitive c-reactive protein,HIV antibody quantification,serum sodium,thrombocytocrit,ESR,glutamic-pyruvic transaminase,eGFR,creatinine
0,1,2020-01-31 01:09:00,73,1,2020-01-30 22:12:47,2020-02-17 12:40:09,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020-01-31 01:25:00,73,1,2020-01-30 22:12:47,2020-02-17 12:40:09,0,NaN,136.0,NaN,...,31.9,NaN,NaN,NaN,NaN,0.12,NaN,NaN,NaN,NaN
2,1,2020-01-31 01:44:00,73,1,2020-01-30 22:12:47,2020-02-17 12:40:09,0,NaN,NaN,103.1,...,NaN,NaN,43.1,NaN,137.7,NaN,NaN,16.0,46.6,130.0
3,1,2020-01-31 01:45:00,73,1,2020-01-30 22:12:47,2020-02-17 12:40:09,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2020-01-31 01:56:00,73,1,2020-01-30 22:12:47,2020-02-17 12:40:09,0,19.9,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def fill_patient_id(df):
    current_patient_id = None
    for index, row in df.iterrows():
        if pd.notna(row['PATIENT_ID']):
            current_patient_id = row['PATIENT_ID']
        else:
            df.at[index, 'PATIENT_ID'] = current_patient_id

    df['PATIENT_ID'] = df['PATIENT_ID'].astype(int)

    return df


def get_last_measurement(df):
    last_measurement = df.groupby('PATIENT_ID').last().reset_index()
    return last_measurement


def calculate_hospital_stay_length(df):
    df['HOSPITAL_STAY_LENGTH'] = (df['Discharge time'] - df['Admission time'])

    df.drop(columns=['Admission time', 'Discharge time'], inplace=True)

    return df    


def preprocess_data(df):
    df = fill_patient_id(df)
    df = get_last_measurement(df)
    df = calculate_hospital_stay_length(df)
    return df


data_preprocessed = preprocess_data(data)
data_test_preprocessed = preprocess_data(data_test)

In [27]:
data_preprocessed.head()

,PATIENT_ID,RE_DATE,age,gender,outcome,Hypersensitive cardiac troponinI,hemoglobin,Serum chloride,Prothrombin time,procalcitonin,...,Activation of partial thromboplastin time,Hypersensitive c-reactive protein,HIV antibody quantification,serum sodium,thrombocytocrit,ESR,glutamic-pyruvic transaminase,eGFR,creatinine,HOSPITAL_STAY_LENGTH
0,1,2020-02-17 08:31:00,73,1,0,19.9,131.0,100.0,12.4,0.09,...,38.9,2.6,0.09,142.7,0.16,41.0,30.0,74.7,88.0,17 days 14:27:22
1,2,2020-02-17 15:34:00,61,1,0,1.9,149.0,98.1,12.3,0.09,...,36.0,27.4,NaN,137.4,0.27,40.0,22.0,94.6,74.0,14 days 15:19:58
2,3,2020-02-06 23:15:00,70,2,0,NaN,126.0,102.2,13.6,0.06,...,34.8,3.6,0.10,143.2,0.23,29.0,67.0,84.6,64.0,16 days 06:52:55
3,4,2020-02-17 08:31:00,74,1,0,4.8,103.0,103.1,16.3,0.38,...,NaN,14.5,0.11,144.2,0.27,72.0,26.0,74.2,88.0,17 days 13:55:13
4,5,2020-02-18 09:35:00,29,2,0,5.6,130.0,102.2,14.6,0.02,...,NaN,0.8,0.08,143.6,0.36,11.0,18.0,122.8,54.0,16 days 13:33:12

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

X = data_preprocessed.drop(columns=["outcome"])
y = data_preprocessed["outcome"]

model.fit(X, y)

# X_test = data_test.drop(columns=["outcome"])
# y_test = data_test["outcome"]

# predictions = model.predict(X_test)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Float64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>)